## What is numpy?

- Fundamental package for scientific computing in python
- Linear algebra
- Array manipulation
- Compiled C

In [1]:
# install Numpy
!pip install numpy



In [3]:
lista = [1, 2, 3]
listb = [1, 2, 3]
listc = []

for aval, bval in zip(lista, listb):
    listc.append(aval + bval)

print(listc)


[2, 4, 6]


In [9]:
import numpy as np

a = np.array([[1, 2, 3]])
b = np.array([[1, 2, 3]])

print("Array 'a':")
print(a)
print("\nArray 'b':")
print(b)

print("Array a + b", a+b)

Array 'a':
[[1 2 3]]

Array 'b':
[[1 2 3]]
Array a + b [[2 4 6]]


In [11]:
a = np.array([
    [1, 2, 3],
    [1, 2, 3]
])

b = np.array([
    [1, 2, 3],
    [1, 2, 3]
])

c = a+b
print(c)

[[2 4 6]
 [2 4 6]]
